# Generated by Django 3.1.6 on 2021-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20210428_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='security',
            field=models.CharField(choices=[('HQLA', 'HQLA'), ('LA', 'LA'), ('ILA', 'ILA'), ('Secured Debt', 'Secured Debt'), ('Unsecured Debt', 'Unsecured Debt'), ('Synthetics', 'Synthetics')], max_length=50),
        ),
    ]
