# Generated by Django 3.1.6 on 2021-04-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20210428_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='post',
        ),
    ]
