# Generated by Django 3.1.6 on 2021-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_auto_20210503_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='trade',
        ),
        migrations.AddField(
            model_name='post',
            name='trade',
            field=models.ManyToManyField(blank=True, null=True, related_name='trade_post', to='fund.Trade'),
        ),
    ]
