# Generated by Django 3.1.6 on 2021-05-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_auto_20210503_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trade',
            field=models.ManyToManyField(blank=True, related_name='trade_post', to='fund.Trade'),
        ),
    ]
