# Generated by Django 3.1.6 on 2021-05-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
